### ISSUE TITLE
请问为什么不考虑用 consul service 提供的服务注册/发现来实现，而选择用kv store存储服务地址呢？

### ISSUE THREAD

**Issue by hankeyyh** [rpcxio/rpcx-consul#2]
define service: https://developer.hashicorp.com/consul/docs/services/usage/define-services
service discovery: https://developer.hashicorp.com/consul/docs/services/discovery/dns-overview

**Comment by smallnest** [comment]
为了能有一个统一的框架支持consul,etcd和zookeeper
